name: Quality Assurance

on: [push]

jobs:
  linter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Analysing the code format with flake8
      run: |
        flake8 `find -path ./venv -prune -false -o -name '*.py'`
